# This is a basic workflow to help you get started with Actions

name: Generate documentation and update readme

# Trigger the workflow on push event for master branch 
# or pull request events but only for the master branch with the type closed
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout bootstrap-functions
      uses: actions/checkout@v2
      with:
        path: bootstrap-functions

    - name: Checkout shdoc
      uses: actions/checkout@v2
      with:
        repository: reconquest/shdoc 
        path: shdoc
    
    - name: Add shdoc to PATH
      run: |
        echo "::add-path::$WORKSPACE_PATH/shdoc"
        echo "$PATH"

    - name: Generate documentation
      run: bash generate_docs.sh

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md docs/
        git commit -m "Update documentation"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
